// React/react-practice/src/components/PostForm.jsx
import React from 'react';
import MyInput from "./UI/input/MyInput";
import MyButton from "./UI/button/MyButton";
import {useState} from "react";

const PostForm = ({create}) => {
    const [post, setPost] = useState({
        title: '',
        body: ''
    })

    const addNewPost = (e) => {
        e.preventDefault();
        const newPost = {
            ...post, id: Date.now()
        }
        create(newPost)
        setPost({title: '', body: ''})
    }


    return (
            <form>
                {
                    /*Управляемый компонент создается через useState
                    привязку value и отслеживание события onChange
                    и достигается двустороннее связывание*/
                }
                <MyInput
                    type="text"
                    placeholder="Название поста"
                    value={post.title}
                    onChange={e => setPost({...post, title: e.target.value})}
                />

                {
                    /*Неуправляемый компонент создается через ref и функцию React.forwardRef*/
                }
                {/*<MyInput*/}
                {/*    type="text"*/}
                {/*    placeholder="Описание поста"*/}
                {/*    ref={bodyInputRef}*/}
                {/*/>*/}

                <MyInput
                    type="text"
                    placeholder="Описание поста"
                    value={post.body}
                    onChange={e => setPost({...post, body: e.target.value})}
                />
                <MyButton
                    onClick={addNewPost}
                >
                    Создать пост
                </MyButton>
            </form>
    );
};

export default PostForm;

// Vue/v3/src/components/PostForm.vue
<template>
  <h3>
    Создание поста
  </h3>
  <form @submit.prevent>
    <my-input
        type="text"
        v-model="post.title"
        placeholder="Название"/>
    <my-input
        type="text"
        v-model="post.body"
        placeholder="Описание"/>
    <my-button
        @click="createPost"
        style="align-self: flex-end; margin-top: 15px "
    >
      Создать
    </my-button>
  </form>
</template>

<script>

export default {
  name: "PostForm",
  data() {
    return {
      post: {
        title: '',
        body: '',
      }
    }
  },

  methods: {
    createPost() {
      this.post.id = Date.now()
       this.$emit('create', this.post);
       this.post = {
         title: '',
         body: ''
       }
    }
  }
}
</script>

<style scoped>
form {
  display: flex;
  flex-direction: column;
}
</style>
